spring:
  elasticsearch:
    username: elastic
    uris: http://localhost:9200
    password: 123456
  datasource:
    name: localhost
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
    username: root
    url: jdbc:mysql://localhost:3306/localhost?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    password: root